version: '3.8'
services:
  mysql:

    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smsGateway
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "14000:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5



  gateway:
      depends_on:
        - conf-server
        - mysql

      build:
        context: gatway
      ports:
        - "7001:7001"
      networks:
        - backend
  discovery:
    build:
      context: discovery
    ports:
      - "8888:8888"
    networks:
      - backend
  conf-server:
    build:
      context: conf-server
    ports:
      - "9000:9000"
    networks:
      - backend
networks:
  backend:
    driver: bridge

