spring:
  application:
    name: conf-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:hakkm/server-conf-sms.git
          default-label: main
server:
  port: 9000
